name: Build

on:
  push:
  pull_request:
    types:
      - opened

jobs:
  build-ios:
    name: Build iOS
    runs-on: macOS-14
    steps:
    - uses: actions/checkout@v4

    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.2'

    - name: Build iOS
      run: xcodebuild -scheme SimultaneouslyScrollView -destination "platform=iOS Simulator,name=iPhone 15 Pro,OS=latest"

  build-tvos:
    name: Build tvOS
    runs-on: macOS-14
    steps:
      - uses: actions/checkout@v4

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.2'

      - name: Build tvOS
        run: xcodebuild -scheme SimultaneouslyScrollView -destination "platform=tvOS Simulator,name=Apple TV 4K (3rd generation),OS=latest"

  build-visionos:
    name: Build visionOS
    runs-on: macOS-14
    steps:
      - uses: actions/checkout@v4

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.2'

      - name: Build visionOS
        run: xcodebuild -scheme SimultaneouslyScrollView -destination "platform=visionOS Simulator,name=Apple Vision Pro,OS=latest"
